import {
    TbBrandCpp,
    DiJavascript,
    SiTypescript,
    FaPython,
    FaReact,
    SiExpress,
    FaNodeJs,
    SiMongodb,
    BiLogoPostgresql,
    TbBrandPrisma,
    SiRedux,
    TbBrandNextjs,
    SiHono,
    IoLogoDocker,
    SiShadcnui,
    RiTailwindCssFill,
    FaGitAlt,
    FaGithub,
    FaUbuntu,
    IoLogoFigma,
    SiTurborepo,
    IoLogoCss3,
  } from "./icon";

 export const skills = [
    { icon: TbBrandCpp },
    { icon: DiJavascript },
    { icon: SiTypescript },
    { icon: FaPython },
    { icon: FaReact },
    { icon: SiExpress },
    { icon: FaNodeJs },
    { icon: SiMongodb },
    { icon: BiLogoPostgresql },
    { icon: TbBrandPrisma },
    { icon: SiRedux },
    { icon: TbBrandNextjs },
    { icon: SiHono },
    { icon: IoLogoDocker },
    { icon: SiShadcnui },
    { icon: RiTailwindCssFill },
    { icon: FaGitAlt },
    { icon: FaGithub },
    { icon: FaUbuntu },
    { icon: IoLogoFigma },
    { icon: SiTurborepo },
    { icon: IoLogoCss3 },
  ];